### ISSUE TITLE
TypeError: Cannot read property "0" from undefined

### ISSUE THREAD

**Issue by vapman** [adamjmurray/bitwig-launch-control#1]
I get this error whenever I try switching to factory preset #2. Bitwig 3.1.2 on macos.
Otherwise, the script works fine, thank you very much.

**Comment by adamjmurray** [comment]
Sorry for the slow response. Thanks for letting me know. I get the error in Bitwig 3.1 too. I'll try to fix it.

**Comment by adamjmurray** [comment]
Ok, I think I found the problem. Try installing the latest version: https://github.com/adamjmurray/bitwig-launch-control/archive/master.zip

That should fix it! Let me know if it doesn't.
